### ISSUE TITLE
Error during  "git submodule update --init --depth 1"

### ISSUE THREAD

**Issue by gampam2000** [dmazzella/ucryptography#1] opened 2023-07-06 11:12 UTC
Hi 
if I follow your steps to compile it, i get the following error at this step:

`/micropython/usercmodule/ucryptography$ git submodule update --init --depth 1`

Cloning into '/micropython/usercmodule/ucryptography/c25519'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:dmazzella/c25519.git' into submodule path '/micropython/usercmodule/ucryptography/c25519' failed
Failed to clone 'c25519'. Retry scheduled
Cloning into 'micropython/usercmodule/ucryptography/c25519'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:dmazzella/c25519.git' into submodule path '/micropython/usercmodule/ucryptography/c25519' failed
Failed to clone 'c25519' a second time, aborting

Any hints on how to fix this?

Thanks & best regards

**Comment by dmazzella** [comment] 2023-07-06 12:06
fixed in [eec3e2f3d0481e36c4064f14a121c34ff81078b0](https://github.com/dmazzella/ucryptography/commit/eec3e2f3d0481e36c4064f14a121c34ff81078b0)

update your local repository and retry

**Comment by gampam2000** [comment] 2023-07-06 14:36
Hi, thanks for the fix, the build for the unix port now worked, but the module was not included when I build micropython for the esp32 port.

I changed then the last compile to: 
make -j2 -C ports/**esp32**/ MICROPY_PY_BTREE=0 MICROPY_SSL_MBEDTLS=1 USER_C_MODULES="$(pwd)/usercmodule"

 I get than the following error:

Including User C Module(s) from /micropython/usercmodule
CMake Error at /micropython/py/usermod.cmake:42 (include):
  include could not find load file:

    /micropython/usercmodule
Call Stack (most recent call first):
  esp32_common.cmake:19 (include)
  main_esp32/CMakeLists.txt:11 (include)

Any ideas what I need to do so that I compile it for the ESP32 port?

Thanks & best regards

**Comment by dmazzella** [comment] 2023-07-06 14:45
For ESP32 in `USER_C_MODULES` must point to `micropython.cmake` no the folder

However at the moment the build with cmake is not tested, I only wrote the file but never tried it

**Comment by gampam2000** [comment] 2023-07-06 15:34
I tested it, build start now but I got than the following error:

[ 82%] Building C object esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/micropython/py/argcheck.c.obj
/micropython/usercmodule/ucryptography/c25519/src/edsign.c: In function 'expand_key':
/micropython/usercmodule/ucryptography/c25519/src/edsign.c:23:29: error: storage size of 's' isn't known
   23 |         struct sha512_state s;
      |                             ^
/micropython/usercmodule/ucryptography/c25519/src/edsign.c:23:29: warning: unused variable 's' [-Wunused-variable]
/micropython/usercmodule/ucryptography/c25519/src/edsign.c: In function 'hash_with_prefix':
/micropython/usercmodule/ucryptography/c25519/src/edsign.c:70:29: error: storage size of 's' isn't known
   70 |         struct sha512_state s;
      |                             ^

I do not need c25519, can I disable this? Or how can I fix the error otherwise?

Thanks & best regards

**Comment by dmazzella** [comment] 2023-07-06 15:46
for now you can disable it in [micropython.cmake](https://github.com/dmazzella/ucryptography/blob/eec3e2f3d0481e36c4064f14a121c34ff81078b0/micropython.cmake#L35
)
```
MICROPY_PY_UCRYPTOGRAPHY_ED25519=0
C25519_USE_MBEDTLS_SHA512=0
```

**Comment by gampam2000** [comment] 2023-07-06 16:40
Hi, ok I tried this, it goes further but than I get a  lot of errors like this:

 98%] Building C object esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/micropython/usercmodule/ucryptography/modcryptography.c.obj
[ 98%] Building C object esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/micropython/usercmodule/ucryptography/BLAKE2/ref/blake2s-ref.c.obj
In file included from /micropython/py/mpstate.h:35,
                 from /micropython/py/runtime.h:29,
                 from /micropython/usercmodule/ucryptography/modcryptography.c:36:
/micropython/py/objexcept.h:44:50: error: 'MP_QSTR_InvalidSignature' undeclared here (not in a function); did you mean 'mp_type_InvalidSignature'?
   44 |     MP_DEFINE_CONST_OBJ_TYPE(mp_type_##exc_name, MP_QSTR_##exc_name, MP_TYPE_FLAG_NONE, \
      |                                                  ^~~~~~~~
/micropython/py/obj.h:777:44: note: in definition of macro 'MP_DEFINE_CONST_OBJ_TYPE_EXPAND'
  777 | #define MP_DEFINE_CONST_OBJ_TYPE_EXPAND(x) x
      |                                            ^
/micropython/py/obj.h:781:179: note: in expansion of macro 'MP_DEFINE_CONST_OBJ_TYPE_NARGS_4'
  781 | #define MP_DEFINE_CONST_OBJ_TYPE_NARGS(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, N, ...) MP_DEFINE_CONST_OBJ_TYPE_NARGS_##N
      |                                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/micropython/py/objexcept.h:44:5: note: in expansion of macro 'MP_DEFINE_CONST_OBJ_TYPE'
   44 |     MP_DEFINE_CONST_OBJ_TYPE(mp_type_##exc_name, MP_QSTR_##exc_name, MP_TYPE_FLAG_NONE, \
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
/micropython/usercmodule/ucryptography/modcryptography.c:66:1: note: in expansion of macro 'MP_DEFINE_EXCEPTION'
   66 | MP_DEFINE_EXCEPTION(InvalidSignature, Exception);
      | ^~~~~~~~~~~~~~~~~~~
/micropython/py/objexcept.h:44:50: error: 'MP_QSTR_AlreadyFinalized' undeclared here (not in a function); did you mean 'mp_type_AlreadyFinalized'?
   44 |     MP_DEFINE_CONST_OBJ_TYPE(mp_type_##exc_name, MP_QSTR_##exc_name, MP_TYPE_FLAG_NONE, \
      |                                                  ^~~~~~~~
/micropython/py/obj.h:777:44: note: in definition of macro 'MP_DEFINE_CONST_OBJ_TYPE_EXPAND'
  777 | #define MP_DEFINE_CONST_OBJ_TYPE_EXPAND(x) x
      |                                            ^
/micropython/py/obj.h:781:179: note: in expansion of macro 'MP_DEFINE_CONST_OBJ_TYPE_NARGS_4'
  781 | #define MP_DEFINE_CONST_OBJ_TYPE_NARGS(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, N, ...) MP_DEFINE_CONST_OBJ_TYPE_NARGS_##N
      |                                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/micropython/py/objexcept.h:44:5: note: in expansion of macro 'MP_DEFINE_CONST_OBJ_TYPE'
   44 |     MP_DEFINE_CONST_OBJ_TYPE(mp_type_##exc_name, MP_QSTR_##exc_name, MP_TYPE_FLAG_NONE, \
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
/micropython/usercmodule/ucryptography/modcryptography.c:67:1: note: in expansion of macro 'MP_DEFINE_EXCEPTION'
   67 | MP_DEFINE_EXCEPTION(AlreadyFinalized, Exception);
      | ^~~~~~~~~~~~~~~~~~~
/micropython/py/objexcept.h:44:50: error: 'MP_QSTR_NotYetFinalized' undeclared here (not in a function); did you mean 'mp_type_NotYetFinalized'?
   44 |     MP_DEFINE_CONST_OBJ_TYPE(mp_type_##exc_name, MP_QSTR_##exc_name, MP_TYPE_FLAG_NONE, \
      |                                                  ^~~~~~~~
/micropython/py/obj.h:777:44: note: in definition of macro 'MP_DEFINE_CONST_OBJ_TYPE_EXPAND'
  777 | #define MP_DEFINE_CONST_OBJ_TYPE_EXPAND(x) x
      |                                            ^
/micropython/py/obj.h:781:179: note: in expansion of macro 'MP_DEFINE_CONST_OBJ_TYPE_NARGS_4'
  781 | #define MP_DEFINE_CONST_OBJ_TYPE_NARGS(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, N, ...) MP_DEFINE_CONST_OBJ_TYPE_NARGS_##N

there are several more errors like this.

Any suggestions on how I could fix this?

Thanks & best regards

**Comment by dmazzella** [comment] 2023-07-06 20:16
try to add:

```
extern const mp_obj_type_t mp_type_InvalidSignature;
extern const mp_obj_type_t mp_type_AlreadyFinalized;
extern const mp_obj_type_t mp_type_NotYetFinalized;
extern const mp_obj_type_t mp_type_UnsupportedAlgorithm;
extern const mp_obj_type_t mp_type_InvalidKey;
extern const mp_obj_type_t mp_type_InvalidToken;
```

[modcryptography.c#L65](https://github.com/dmazzella/ucryptography/blob/eec3e2f3d0481e36c4064f14a121c34ff81078b0/modcryptography.c#L65)

**Comment by dmazzella** [comment] 2023-07-06 21:37
the problem is:

- `#if defined(MICROPY_PY_UCRYPTOGRAPHY)` in [modcryptography.c#L27](https://github.com/dmazzella/ucryptography/blob/eec3e2f3d0481e36c4064f14a121c34ff81078b0/modcryptography.c#L27) 
-  `#endif // MICROPY_PY_UCRYPTOGRAPHY` in  [modcryptography.c#L6779C1-L6779C35](https://github.com/dmazzella/ucryptography/blob/eec3e2f3d0481e36c4064f14a121c34ff81078b0/modcryptography.c#L6779C1-L6779C35)

please comment it and retry, sorry

**Comment by gampam2000** [comment] 2023-07-07 07:06
Good morning, I tried it and now I get the following errors:

 98%] Building C object esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/__/__/frozen_content.c.obj
[ 98%] Building C object esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/micropython/usercmodule/ucryptography/BLAKE2/ref/blake2s-ref.c.obj
In file included from /micropython/lib/mbedtls/include/mbedtls/gcm.h:82,
                 from /micropython/usercmodule/ucryptography/modcryptography.c:183:
/esp-idf/components/mbedtls/port/include/gcm_alt.h:30:37: error: conflicting types for 'esp_aes_gcm_starts'; have 'int(mbedtls_gcm_context *, int,  const unsigned char *, size_t,  const unsigned char *, size_t)' {aka 'int(esp_gcm_context *, int,  const unsigned char *, unsigned int,  const unsigned char *, unsigned int)'}
   30 | #define mbedtls_gcm_starts          esp_aes_gcm_starts
      |                                     ^~~~~~~~~~~~~~~~~~
/micropython/lib/mbedtls/include/mbedtls/gcm.h:243:5: note: in expansion of macro 'mbedtls_gcm_starts'
  243 | int mbedtls_gcm_starts(mbedtls_gcm_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~
In file included from /esp-idf/components/mbedtls/port/include/gcm_alt.h:22,
                 from /micropython/lib/mbedtls/include/mbedtls/gcm.h:82,
                 from /micropython/usercmodule/ucryptography/modcryptography.c:183:
/esp-idf/components/mbedtls/port/include/aes/esp_aes_gcm.h:88:5: note: previous declaration of 'esp_aes_gcm_starts' with type 'int(esp_gcm_context *, int,  const unsigned char *, size_t)' {aka 'int(esp_gcm_context *, int,  const unsigned char *, unsigned int)'}
   88 | int esp_aes_gcm_starts( esp_gcm_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~
In file included from /micropython/lib/mbedtls/include/mbedtls/gcm.h:82,
                 from /micropython/usercmodule/ucryptography/modcryptography.c:183:
/esp-idf/components/mbedtls/port/include/gcm_alt.h:32:37: error: conflicting types for 'esp_aes_gcm_update'; have 'int(mbedtls_gcm_context *, size_t,  const unsigned char *, unsigned char *)' {aka 'int(esp_gcm_context *, unsigned int,  const unsigned char *, unsigned char *)'}
   32 | #define mbedtls_gcm_update          esp_aes_gcm_update
      |                                     ^~~~~~~~~~~~~~~~~~
/micropython/lib/mbedtls/include/mbedtls/gcm.h:275:5: note: in expansion of macro 'mbedtls_gcm_update'
  275 | int mbedtls_gcm_update(mbedtls_gcm_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~
In file included from /esp-idf/components/mbedtls/port/include/gcm_alt.h:22,
                 from /micropython/lib/mbedtls/include/mbedtls/gcm.h:82,
                 from /micropython/usercmodule/ucryptography/modcryptography.c:183:
/esp-idf/components/mbedtls/port/include/aes/esp_aes_gcm.h:168:5: note: previous declaration of 'esp_aes_gcm_update' with type 'int(esp_gcm_context *, const unsigned char *, size_t,  unsigned char *, size_t,  size_t *)' {aka 'int(esp_gcm_context *, const unsigned char *, unsigned int,  unsigned char *, unsigned int,  unsigned int *)'}
  168 | int esp_aes_gcm_update( esp_gcm_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~
In file included from /micropython/lib/mbedtls/include/mbedtls/gcm.h:82,
                 from /micropython/usercmodule/ucryptography/modcryptography.c:183:
/esp-idf/components/mbedtls/port/include/gcm_alt.h:33:37: error: conflicting types for 'esp_aes_gcm_finish'; have 'int(mbedtls_gcm_context *, unsigned char *, size_t)' {aka 'int(esp_gcm_context *, unsigned char *, unsigned int)'}
   33 | #define mbedtls_gcm_finish          esp_aes_gcm_finish
      |                                     ^~~~~~~~~~~~~~~~~~
/micropython/lib/mbedtls/include/mbedtls/gcm.h:296:5: note: in expansion of macro 'mbedtls_gcm_finish'
  296 | int mbedtls_gcm_finish(mbedtls_gcm_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~
In file included from /esp-idf/components/mbedtls/port/include/gcm_alt.h:22,
                 from /micropython/lib/mbedtls/include/mbedtls/gcm.h:82,
                 from /micropython/usercmodule/ucryptography/modcryptography.c:183:
/esp-idf/components/mbedtls/port/include/aes/esp_aes_gcm.h:206:5: note: previous declaration of 'esp_aes_gcm_finish' with type 'int(esp_gcm_context *, unsigned char *, size_t,  size_t *, unsigned char *, size_t)' {aka 'int(esp_gcm_context *, unsigned char *, unsigned int,  unsigned int *, unsigned char *, unsigned int)'}
  206 | int esp_aes_gcm_finish( esp_gcm_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~
/micropython/usercmodule/ucryptography/modcryptography.c: In function 'ec_sign':
/micropython/usercmodule/ucryptography/modcryptography.c:1803:21: error: implicit declaration of function 'time' [-Werror=implicit-function-declaration]
 1803 |     srand((unsigned)time(&t));
      |                     ^~~~
cc1: some warnings being treated as errors
make[3]: *** [esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/build.make:3234: esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/micropython/usercmodule/ucryptography/modcryptography.c.obj] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/micropython/ports/esp32/build-GENERIC'
make[2]: *** [CMakeFiles/Makefile2:4742: esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/all] Error 2
make[2]: Leaving directory '/micropython/ports/esp32/build-GENERIC'
make[1]: *** [Makefile:130: all] Error 2
make[1]: Leaving directory '/micropython/ports/esp32/build-GENERIC'
HINT: Please check that the function name is correct. Also it is possible that you've forgot to import time library(s) in header file or add the necessary REQURIES component. Try to add missing libraries to your project header file or check idf_component_register(REQUIRES ...) section in your component CmakeList.txt file. For more information run 'idf.py docs -sp api-guides/build-system.html'.
Also, please check if the function has been removed, renamed or replaced by an alternative function - refer to the migration guide for more information.
make failed with exit code 2, output of the command is in the /micropython/ports/esp32/build-GENERIC/log/idf_py_stderr_output_881667 and /micropython/ports/esp32/build-GENERIC/log/idf_py_stdout_output_881667
-e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make: *** [Makefile:56: all] Error 1
make: Leaving directory '/micropython/ports/esp32'

Any suggestions on how I could fix this?

Thanks & best regards

**Comment by dmazzella** [comment] 2023-07-07 07:48
Good morning,

this error is due to the fact that esp32 implements an alternative function (which takes advantage of hardware acceleration) for aes_gcm

`/esp-idf/components/mbedtls/port/include/gcm_alt.h:30:37: error: conflicting types for 'esp_aes_gcm_starts';`

to fix this I need some time, esp32 is not the target for this library, but as soon as possible I will get my hands on it and integrate it

Regards

**Comment by gampam2000** [comment] 2023-07-07 10:46
Hi, 

I really appreciate your effort & help. 
Any Idea on how long this would take? Days, Weeks?

Thanks & best regards!

**Comment by dmazzella** [comment] 2023-07-13 22:02
close first issue, for ESP32 I will open a new issue when I come back to it

**Closed as completed by dmazzella** 2023-07-13 22:02 UTC
Labels: enhancement, good first issue
